name: RandomMythicBosses
version: 1.1
author: wbe
main: wbe.randommythicbosses.RandomMythicBosses
depend: [MythicMobs]
api-version: 1.20.4
commands:
  RandomMythicBosses:
    description: Main command
    aliases: [rmb, randommythicbosses]
    permission: randommythicbosses.command
